### ISSUE TITLE
configuration problems

### ISSUE THREAD

**Issue by jcc2303** [lasso-js/lasso-marko#2]
Hi,

We are having problems trying to get lasso-marko to work for our Koa server. 
This is our current render setup.

```js
'use strict';

let marko = require('./marko-config');

function findTemplate(template) {
  console.log(template);
  return `../../views/pages/${template}/${template}.marko`
}

function resolveTemplate(templateName) {
  let templatePath = findTemplate(templateName);
  return require.resolve(templatePath);
}

module.exports =  function(response, template, data) {
  console.log('render - template', template);
  let resolvedTemplate = resolveTemplate(template);
  console.log(resolvedTemplate);
  response.body = marko.load(template).stream(data);
  response.type = 'text/html';
}
```

In our registration page folder we have an empty `registration.browser.json` 

```json
{
    "dependencies": [
    ]
}
```

```html
<layout-use template="../../layouts/application-layout.marko" >
    <layout-put into="body" >
      <div class="container" id="content">
          <div id="registration-form" class="container">
          </div>
      </div>
    </layout-put>
</layout-use>
```

We get this error

```bash
Koa appplication render service listens on port 4004
render - template registration
registration
/home/javiercabrera/smi-workspace/rapid-render/views/pages/registration/registration.marko

  Error: ENOENT: no such file or directory, open '/home/javiercabrera/smi-workspace/rapid-render/registration'
      at Error (native)
      at Object.fs.openSync (fs.js:549:18)
      at Object.fs.readFileSync (fs.js:397:15)
      at load (/home/javiercabrera/smi-workspace/rapid-render/node_modules/marko/runtime/loader.js:41:23)
      at Object.load (/home/javiercabrera/smi-workspace/rapid-render/node_modules/marko/runtime/marko-runtime.js:230:44)
      at module.exports (/home/javiercabrera/smi-workspace/rapid-render/lib/server/render.js:20:25)
      at Object.<anonymous> (/home/javiercabrera/smi-workspace/rapid-render/lib/server/route.js:10:7)
      at GeneratorFunctionPrototype.next (native)
      at Object.dispatch (/home/javiercabrera/smi-workspace/rapid-render/node_modules/koa-router/lib/router.js:97:44)
      at GeneratorFunctionPrototype.next (native)
      at Object.serve (/home/javiercabrera/smi-workspace/rapid-render/node_modules/koa-static/index.js:41:14)
      at GeneratorFunctionPrototype.next (native)
      at onFulfilled (/home/javiercabrera/smi-workspace/rapid-render/node_modules/koa/node_modules/co/index.js:65:19)
      at lib$es6$promise$$internal$$tryCatch (/home/javiercabrera/smi-workspace/rapid-render/node_modules/axios/node_modules/es6-promise/dist/es6-promise.js:331:16)
      at lib$es6$promise$$internal$$invokeCallback (/home/javiercabrera/smi-workspace/rapid-render/node_modules/axios/node_modules/es6-promise/dist/es6-promise.js:343:17)
      at lib$es6$promise$$internal$$publish (/home/javiercabrera/smi-workspace/rapid-render/node_modules/axios/node_modules/es6-promise/dist/es6-promise.js:314:11)
```

**Comment by patrick-steele-idem** [comment]
Hi @jcc2303, you didn't share the code for your page templates but I suspect you missing the required Lasso.js tags for Marko. Are you including the `<lasso-page>`, `<lasso-head>` and `<lasso-body>` tags? Those tags do the work of injecting the required `<script>` and `<link>` tags into your rendered HTML. Please see: [Using Lasso.js Taglib with Marko](https://github.com/lasso-js/lasso#using-lassojs-taglib-with-marko) 

If you are using those tags and are still seeing the problem then please let me know. I hope that helps.
